---
- name: To install nginx, PHP, and MariaDB
  hosts: 192.168.15.15
  become: yes
  become_user: root
  tasks:
    # NGINX
    - name: Enabling nginx on amazonlinux
      shell: "amazon-linux-extras enable nginx1.12"
    - name: Installing nginx
      yum:
        name: nginx
        state: present
    - name: Copy NGINX config files to a specific folder
      copy:
        src: "./files/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644
    
    # PHP
    - name: Installing PHP
      command: "{{item}}"
      loop:
        - yum install php && yum install php-common && yum install php-cli
        - yum install php-curl && yum install php-gd && yum install php-mysql
        - yum install php-fpm
    - name: Copy PHP conf files to a specific folder
      copy:
        src: "./files/php.conf"
        dest: "/etc/php-fpm.d/www.conf"
        mode: 0644
    - name: Setting permissions
      file:
        path: /var/lib/php
        owner: root
        group: nginx
    - name: Enabling php-fpm
      service: name=php-fpm enabled=yes
    - name: start php-fpm
      service: 
        name: php-fpm
        state: started
    - name: creating a directory
      file:
        path: "/var/www/app"
        state: directory
    - name: Package installer
      local_action: shell tar -czf app.zip -C ./files/php .
      become: no
    - name: Copy package from one location to another
      copy:
        src: "app.zip"
        dest: "/home/ec2-user/app.zip"

    - name: Unpacking using tar package manager
      shell: "tar -xf /home/ec2-user/app.zip -C /var/www/app"
    
    - name: Setting permissions to app directory
      file:
        path: /var/www/app
        owner: root
        group: nginx

    - name: Changing the location for app.conf
      copy: 
        src: "./files/application.conf"
        dest: "/etc/nginx/conf.d/app.conf"
        mode: 0644

    - name: Enable Nginx
      service: name=nginx enabled=yes
      become: yes
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    # # MARIADB
    - name: Enabling MariaDB on amazonlinux
      shell: "amazon-linux-extras enable mariadb10.5"
    - name: Installing MariaDB
      yum:
        name: mariadb
        state: present
    - name: Enabling MariaDB
      shell: "systemctl enable mariadb"
    - name: Starting MariaDB
      shell: "systemctl start mariadb"
    - name: Creating database inside MariaDB
      shell:
        cmd: |
          mariadb <<EOF
          DROP USER IF EXISTS user_manager;
          DROP DATABASE IF EXISTS user_inventory;
          CREATE DATABASE user_inventory;
          CREATE USER user_manager IDENTIFIED BY 'Qwerty123';
          GRANT ALL PRIVILEGES ON user_inventory.* TO user_manager;
          EOF
    - name: Copy DB DDL file
      copy:
        src: "./files/user_management.sql"
        dest: "/home/ec2-user/user_management.sql"
        mode: 0644 # owner=rw/group=r/others=r
    - name: Build database tables
      shell: "mariadb user_inventory < /home/ec2-user/user-management.sql"
