---
- name: To install nginx, PHP, and MariaDB
  hosts: 172.48.15.15
  become: yes
  become_user: root
  tasks:
    # NGINX
    - name: Enabling nginx on amazonlinux
      shell: "amazon-linux-extras enable nginx1.12"
    - name: Installing nginx
      yum:
        name: nginx
        state: present
    - name: Moving html file
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
    - name: start nginx server
      service:
        name: nginx
        state: started